FROM node:20

RUN apt update

RUN apt install -y zsh

RUN sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

RUN mkdir back

WORKDIR /back

COPY package*.json ./

RUN npm install

EXPOSE 8080/tcp

CMD ["npm", "run", "start:dev"]